
EXTRA_CFLAGS += -Idrivers/modem/include

obj-$(CONFIG_NEZHA_HSIC_LINK) += nezha_hsic_serial.o
obj-$(CONFIG_NEZHA_HSIC_LINK_PM) += nezha_hsic_pm.o
obj-$(CONFIG_NEZHA_WUKONG_LOAD) += wukong_assert.o wukong_boot.o \
			wukong_load.o modem_state_notify.o
obj-$(CONFIG_TTY_MUX_TS0710) += ts0710_mux.o
obj-$(CONFIG_NEZHA_AUDIO_STUB) += audiostub.o audiochannel.o
obj-$(CONFIG_NEZHA_NZNET) += ccinet.o N_NZNET.o
obj-$(CONFIG_NEZHA_GADGET_LDISC) += gadget_ldisc.o
